umn-asr/courses

- Gemfile
- Gemfile.lock
- config/application.rb
- config/deploy.rb
- config/deploy/production.rb
- config/environments/development.rb
- config/environments/staging.rb
- config/secrets.yml
This is a bunch of small fixes that enable capistrano deployment for
both Staging and Production. It also adds Oracle & ActiveRecord.
The configuration files "database.yml" and "environment_variables.rb" are being managed by Ansible.
> Update Capistrano deployment for Oracle & Production

- Gemfile.lock
- app/controllers/campuses_controller.rb
- app/controllers/courses_controller.rb
- app/controllers/terms_controller.rb
- app/models/entities/term.rb
- app/models/persisters/active_record/term.rb
- app/models/repositories/term_repository.rb
- app/views/campuses/index.rabl
- app/views/courses/index.rabl
- app/views/terms/index.rabl
- config/routes.rb
- db/migrate/20150303205821_add_terms_table.rb
- db/schema.rb
- db/seeds.rb
- spec/models/entities/term_entity_spec.rb
- spec/models/persisters/active_record/term_spec.rb
- spec/requests/get_campuses_spec.rb
- spec/requests/get_courses_spec.rb
- spec/requests/get_terms_spec.rb
Adds routes to display all campuses and all available terms.  I branched off of iw/feature/add_term_resource, so this pull request also includes Ian's work to add a term resource.
> Adds terms and campuses routes

- app/controllers/courses_controller.rb
- app/models/campus.rb
- app/models/course.rb
- app/models/term.rb
- db/migrate/20150309204641_add_courses_table.rb
- db/schema.rb
- spec/models/course_spec.rb
- spec/models/term_spec.rb
Adds a course model to persist courses that are posted to our
courses controller. Currently, only saving the courses model, still pulls
data from the courses_example.json file for the courses/index route.  Next step is to pull course data from data store.
> Adds the course model

- app/views/courses/show.rabl
- test/fixtures/courses_example.json
This data isn't in the source xml, so we're removing it. Fixes #17
> Remove employee_id from fixture, views

- README.md
- app/controllers/courses_controller.rb
- app/models/course.rb
- app/models/course_attribute.rb
- db/migrate/20150316154025_create_attributes_table.rb
- db/migrate/20150316155616_add_attributes_courses.rb
- db/schema.rb
- db/seeds.rb
- spec/models/course_attribute_spec.rb
- spec/requests/create_courses_spec.rb
- spec/requests/search_courses_spec.rb
- Adds a table for the resource, and a join table for the many-to-many lookup.
- Populates CourseAttribute with seed data
- Saves a CourseAttribute when data posted
- Returns CourseAttribute data when displaying a Course
- Test of CourseAttribute model behavior
> Implement CourseAttribute resource

- app/controllers/courses_controller.rb
- app/models/course.rb
- app/models/section.rb
- db/migrate/20150316203631_create_sections.rb
- db/schema.rb
- db/seeds.rb
- spec/models/section_spec.rb
- spec/requests/create_courses_spec.rb
- Creates sections table
- Populate sections from fixture when seeding db
- Return section resources in GET
- Persist section resources on POST
> Add Section resource

- app/controllers/courses_controller.rb
- app/models/instructor.rb
- app/models/instructor_contact.rb
- app/models/instructor_role.rb
- app/models/section.rb
- db/migrate/20150318002539_create_instructor_contacts.rb
- db/migrate/20150318002610_create_instructor_roles.rb
- db/migrate/20150318002652_create_instructors.rb
- db/schema.rb
- db/seeds.rb
- doc/resources/instructor.yml
- spec/models/instructor_spec.rb
- test/fixtures/courses_example.json
- Adds models to persist Instructor data
- Intructors is just a join table between Sections, InstructorContacts, IntructorRoles.
- Renames employee to instructor. details f9c6929
- Links Instructor to section
- Update db seeding
- Updates courses controller
> Add instructor resources

- app/controllers/courses_controller.rb
- app/models/day.rb
- app/models/location.rb
- app/models/meeting_pattern.rb
- app/models/section.rb
- db/migrate/20150318010910_create_meeting_patterns.rb
- db/migrate/20150318013354_create_locations.rb
- db/migrate/20150318013429_add_location_id_to_meeting_pattern.rb
- db/migrate/20150318013845_create_days.rb
- db/migrate/20150318014312_create_days_meeting_patterns.rb
- db/schema.rb
- db/seeds.rb
- Adds models to persist meeting patterns, locations and days.
- Updates to seeding
- Updates to courses controller to persist and return meeting patterns
> Add meeting patterns resources

- app/controllers/courses_controller.rb
- app/models/presenters/courses_presenter.rb
- app/models/serializer.rb
I tested this in Staging and saw significant speed benefits. With the built-in Ruby JSON my test request took about 900 ms. With Oj, about 100 ms.
> A test of using Oj for json serialization.

- config/schedule.rb
Update schedule.rb to use the cache-refreshing version of the import rake task.
> Update cron task configuration 

- Gemfile
- Gemfile.lock
> Upgrade QueryStringSearch

- app/models/course.rb
- app/services/course_json_import.rb
- db/migrate/20150610180627_add_offer_frequency.rb
- db/schema.rb
- doc/resources/course.yml
- test/fixtures/courses_example.json
- test/fixtures/no_grading_basis_for_section_102.json
- test/fixtures/no_instruction_mode_for_section_104.json
Closes #101
Field added to the table, model, examples and is tested.
> Add offer_frequency attribute to course

- config/deploy.rb
- config/monit/courses_redis_monit
And add monit steps to the deployment
> Add monit config to watch Redis

- config/environments/production.rb
- config/initializers/cache.rb
- lib/cache_pool/lib/cache_pool.rb
Without these changes I'm unable to start this app in an enviroment that
uses caching (Staging & Production)
> Make cache_pool deployable

- config/environments/production.rb
Fixes #141 
Debug is way to chatty and our logs are bloating.
> Change log level to warn in prod

- config/monit/courses_redis_monit
Redis is now deployed in /swadm/bin
> Update monit commands

- app/services/course_json_import.rb
- db/migrate/20170126193550_remove_course_term_id.rb
A few small changes bundled together into a single PR
- Remove an unused and empty column from Courses
- Fixes #155
> Import fixes

- Gemfile
- Gemfile.lock
- config/application.rb
- config/environments/production.rb
- config/environments/staging.rb
- config/initializers/lograge.rb
[Finishes #158059719](https://www.pivotaltracker.com/story/show/158059719)
> Add lograge and logstash for Splunk

- Capfile
- Gemfile
- config/deploy.rb
[#160285558](https://www.pivotaltracker.com/story/show/160285558)
Following the steps outlined in the Knowledge Bucket.
https://github.umn.edu/asrweb/knowledgebucket/blob/master/servers/logrotate.md
> Add logrotate setup to deploy

- README.md
- script/bootstrap
- script/console
- script/deploy
- script/setup
- script/test
- script/update
Closes #187
Closes #188
- Add basic scripts from [our script templates](https://github.umn.edu/asrweb/script_templates)
- Update README to:
- reference those scripts
- include URLs section
- add table of contents
> Upgrade to Maintainability Level 1

- Capfile
> Resolve Capistrano deprecation warning

- README.md
- script/setup
> Switch default branch to main

- README.md
- script/server
* Fixes #213.
* Finishes [this Pivotal Tracker story](https://www.pivotaltracker.com/story/show/183642390).
This is the last thing missing for [Maintainability level 1](https://github.umn.edu/asrweb/knowledgebucket/blob/b225d5b0146855fa713b0944d0b70986f5ff7319/best_practices/maintainability_standards.md#level-1).
> Add script/server
