umn-asr/courses

app/controllers/courses_controller.rb
app/models/campus.rb
app/models/term.rb
spec/models/campus_spec.rb
spec/models/term_spec.rb

Oracle (or the oracle adapter, I'm not sure), does not like it when I
override an active_record primary_key. Attempts to save record results
in errors about NULL id fields. This primary_key overriding was a little
weird anyway, so I'm taking it out.
This also means I have to change the finders used in the
courses_controller, since they can no longer use the basic `find` method

Remove overrides of primary_keys

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/courses_controller.rb
app/models/courses_presenter.rb
app/views/campuses/index.rabl
app/views/campuses/show.rabl
app/views/courses/index.rabl
app/views/courses/show.rabl
app/views/terms/index.rabl
app/views/terms/show.rabl
config/initializers/rabl.rb
spec/requests/get_campuses_spec.rb
spec/requests/get_terms_spec.rb

Main changes:
- Full rabl template for a course, complete with all sub-resources
- Using rabl's partials to re-use templates
- Removed Rails::API as it wouldn't let me set an xml content type (or I couldn't figure out how to do it)
- Introduce CoursesPresenter so that the CoursesController#index only sets one instance var

complete rabl templates

---

app/controllers/courses_controller.rb
app/models/course.rb
app/views/courses/show.rabl
db/seeds.rb
spec/requests/create_courses_spec.rb
spec/requests/get_courses_spec.rb
test/fixtures/courses_example.json

Now that we have a course model, the controller has been updated to pull what it can from the data store instead of using the json reference file. We are still using the reference file for the data we are not currently storing in the data store - as new models are added, this will be updated.

pull course model data from data store

---

Rakefile

This require prevents rake usage when this app is deployed, since the
deployed version don't install rspec.
But it turns out this require isn't even necessary, because of
rspec-rails. I discovered that here:
http://stackoverflow.com/questions/16812989/how-should-i-structure-a-rakefile-with-some-tasks-that-need-to-run-during-deploy#comment24404027_16853639
I did a test deploy with this line removed and Rake tasks work on the
server. And tests still work when doing development locally.
Fixes #19

Remove rspec require

---

Capfile
config/deploy/production.rb
config/deploy/staging.rb

This requires two changes. First, include the rails/migrations file.
2nd, give the deploy the 'db' role
Fixes #18

Configure Capistrano to run migrations on deploy

---

README.md
app/models/searchable_courses.rb
spec/requests/search_courses_spec.rb

Implements #29 
Straightforward feature. We just have to expose `locations` through a method in the SearchableCourse class.

Add ability to search by location

---

app/controllers/courses_controller.rb
app/models/course.rb
app/models/equivalency.rb
db/migrate/20150323143938_create_equivalencies.rb
db/migrate/20150323151217_add_equivalency_association_to_courses.rb
db/schema.rb
db/seeds.rb
spec/models/equivalency_spec.rb

Add Equivalency resource. Has one to many relationship with Courses. Adjust seeds.rb and CoursesController#create to import equivalency data from json, when it is present
Some MeetingPatterns have no Location, so update seeds.rb and CoursesController#create to only try to add them when the data is present
We were running into some data errors because we were trying to persist objects that have already been created - Subjects in seeds.rb and Term and Campus in CoursesController#create - use find_or_create_by instead

JSON Import Tweaks - Add Equivalency, Support for Optional Resources

---

app/models/course_attribute.rb
db/seeds.rb
spec/models/course_attribute_spec.rb

Crookston and Duluth have their own course attribute families, "GE" for Crookston and "DLE" for Duluth. They are mostly different than the CLE attributes but there is at least one overlap in the Duluth attribute ids. 
Change the CourseAttribute validation to require uniqueness of the family + attribute_id combination, rather than just attribute_id so these other attributes can be added. Adjust the seeds import to build the attributes as we get them from the export file.

Support Other Campus' Course Attributes

---

app/views/courses/show.rabl

Most courses do not have an equivalency. In these cases the "equivalency" json key is displaying with a value of null. Change the template to only show the node when there is an equivalency

Conditionally display equivalency

---

app/controllers/courses_controller.rb
app/models/campus.rb
app/models/course.rb
app/models/subject.rb
app/models/term.rb
db/migrate/20150408205348_add_campus_id_and_term_id_to_subjects.rb
db/migrate/20150408205701_remove_campus_id_and_term_id_from_courses.rb
db/schema.rb
db/seeds.rb
spec/models/course_spec.rb
spec/models/subject_spec.rb
spec/rails_helper.rb

Change the association of campus and term from Course to Subject. Subjects vary from campus to campus, so JOUR in the Twin Cities can be different than JOUR in Duluth. This was causing subject to be nil when there was near but not quite subject matches from campus to campus. (See Issue #45).
Change subject to be campus and term specific to address this. This also allows us to redo that data model so that course no longer directly needs the term and campus association. Most of these changes are directly related to that change as well as adding a scope to course so the CoursesController can still fetch the appropriate courses for the term and campus. 
Indirectly related changes include redoing some validations (f0cc5cb, c907800).
In an unrelated change, changed the rspec configuration to …

Associate Subject with Campus and Term

---

app/controllers/courses_controller.rb
config/environments/production.rb
config/environments/staging.rb

Fixes issue #46
The import of data takes a long time (currently several hours). So our
plan is to rely on the cached data until we complete importing the new
data.
To support this, I'm greatly increasing the caching time to 48 hours.
Two days is more than we need, since we plan on importing new data once
a day. But I want to make sure that the cache will last until we
invalidate it after the import.

Increase caching time to 2 days

---

README.md
app/models/course.rb
app/models/searchable_courses.rb
app/views/courses/show.rabl
db/seeds.rb
doc/resources/course.yml
spec/requests/search_courses_spec.rb
test/fixtures/courses_example.json

Fixes #38 
'CLE' as a family of course attributes only applies to UMNTC campuses. Duluth, Rochester, and Morris each have their own attribute family for these Lib Ed/Gen Ed classes (Crookston, as far as I can tell, has no such attribute).
Previous implementation only allowed for searching and displaying attributes that were CLE. So other campuses had nothing. This PR:
- Removes the UMNTC-specific terminology
- Adds the ability to search by course_attribute_family
- Renames cle_attribute_id search criteria to course_attribute_id
- Documents & tests the attribute searching changes
This PR will also require the data importing code to use the node name `course_attributes` instead of `cle_attributes`. I've told @davinlagerroos about this change.

Allow all campuses to do Lib Ed/Gen Ed searches

---

Gemfile
Gemfile.lock
config/application.rb

Using rack-cors to allow the API to be used by sites on other domains.
Setup is currently pretty simple, allow all GET requests.
Fixes #52

Use rack-cors to set access headers

---

app/views/attributes/show.rabl
app/views/combined_sections/show.rabl
app/views/days/show.rabl
app/views/equivalencies/show.rabl
app/views/grading_bases/show.rabl
app/views/instruction_modes/show.rabl
app/views/instructors/show.rabl
app/views/locations/show.rabl
app/views/meeting_patterns/show.rabl
app/views/sections/show.rabl
app/views/subjects/show.rabl

I thought that caching each resource was necessary, but it's currently
not.
We only display the sub-resources of Course as part of a course. And
Rabl currently caches all of the sub-resources as part of Course, thanks
to the cache command in the /courses/show.rabl view.
Removing the caching of the sub-resources has no effect on performance.
It does have the nice effect of making our Redis store a lot smaller.

Remove unnecessary RABL caching.

---

app/models/campus.rb
app/models/presenters/course_presenter.rb
app/models/presenters/courses_presenter.rb
app/models/queryable_course.rb
app/models/queryable_courses.rb
app/models/term.rb
app/services/cache_warmer.rb
app/services/rack_cache_manager.rb
config/application.rb
config/environments/production.rb
config/environments/staging.rb
config/environments/test.rb
config/initializers/cache_pool.rb
lib/cache_pool.rb
lib/tasks/json_import.rake
spec/lib/cache_pool_spec.rb
spec/services/cache_warmer_spec.rb
spec/services/rack_cache_manager_spec.rb

Once the json file import completes we need to update our cache with the new information. However, we rely heavily on caching for performance so we do not want to just wipe the cache and have user requests potentially hitting active record while the cache rebuilds. Because a redis instance supports multiple databases, the app can run off the current database while we cache model information into a cache backed by a different database. 
The CachePool singleton handles keeping track of the redis cache stores so we can put the new data into the "next" cache. CachePool also has a next! method that makes the rebuilt database the current one in the pool. The rebuild is handled by CacheWarmer which knows the objects that need caching. For this to work the models and presenters needed to have …

Add Cache Rebuild and Rotation

---

app/models/presenters/meeting_pattern_presenter.rb
app/views/sections/show.rabl
spec/models/presenters/meeting_pattern_presenter_spec.rb

A couple of updates to our output format to make it match the sample json:
1. Dates should be returned in a yyyy-mm-dd format. We were returning them in a date/time format. Right now, this only effects MeetingPatterns, so this pull request gives this knowledge to MeetingPatternPresenter. If we have other dates, this should get extracted into something else  
2. In sections, credits minimum should appear before credits maximum

Json Formatting Fixes

---

app/models/queryable_course.rb
app/models/queryable_courses.rb

For some reason I made this more complex than it needs to be. I was
caching each queryable course individually, and then caching a
collection of all the queryable course ids. So reading them out of the
cache required two steps:
1. Retrieve the keys
2. Retrieve a queryable course for each key
I was probably doing this because of either a speed concern or because
of the idea that small cache entries are better than big cache entries.
But the speed of this approach is equivalent to just have one big cache
entry of queryable_courses. And since we always retrieve a collection of
queryable_courses, we might as well cache them as a collection. Also, it
makes the code way easier to parse.

Simplify caching of QueryableCourse(s)

---

app/services/course_attribute_json_import.rb
app/services/course_json_import.rb
app/services/equivalency_json_import.rb
db/seeds.rb
lib/tasks/json_import.rake
spec/services/course_attribute_json_import_spec.rb
spec/services/course_json_import_spec.rb
spec/services/equivalency_json_import_spec.rb

We are getting validation errors on duplicate CourseAttributes when we try to import them in parallel. This pull request extracts setting up CourseAttributes from CourseJsonImport so that import can be run in separately. Hopefully this avoids the uniqueness violations but we still get the time savings of running the twin cities course imports in parallel. 
We have not seen problems with Equivalencies yet (they are rarer) but they are also shared across terms, so extracting that setup as well.

Extract Equivalency and CourseAttribute import out of CourseJsonImport

---

config/routes.rb

That's where the useful information is, so we might as well send people
there.

Set root route to redirect to github pages

---

app/controllers/courses_controller.rb
spec/requests/get_courses_spec.rb

Fixes #60
This fix is not my favorite, but I'm hard pressed to think of a reason
why we need something else. As this is the only place in the application
where we have to ask about the null-ness of the Campus & Term, we might
as well just do it in a conditional.

Return 404 if url has invalid campus/term

---

app/controllers/courses_controller.rb
config/initializers/cache.rb
lib/cache_pool.rb
spec/lib/cache_pool_spec.rb

Fixes #76
This commit sets a default cache expiration time in the caching
initializer. It then configures our two caches to use that time. The
http caching calls in the controller also uses the default time.

Configure cache expiration time in one place

---

app/services/cache_warmer.rb
spec/services/cache_warmer_spec.rb

fixes #86 with baf5f74. 
When reusing a cache from the CachePool pool, we need to make sure no old data lingers when we warm it with the current data. Because the redis cache is implemented as an ActiveSupport::Cache::Store we can use the #clear method of the ActiveSupport::Cache::Store api

Clear cache before populating

---

app/models/course.rb
spec/models/course_spec.rb

Fixes #95
The scope that is used to return our sets of courses is
`for_campus_and_term`, so I've only added and tested the ordering there.

Return courses ordered by subject description, catalog number

---

app/models/course.rb
app/models/meeting_pattern.rb
app/models/queryable_course.rb
app/models/section.rb
app/services/course_json_import.rb
spec/services/course_json_import_spec.rb
test/fixtures/no_grading_basis_for_section_102.json
test/fixtures/no_instruction_mode_for_section_104.json

While testing the updated course xml service we encountered several instances where data that we were requiring (e.g. grading basis, instruction mode) was not present, and its absence was causing errors with the import. While this was test data, we were told similarly incomplete data could occur in production if the course was not set up properly in PeopleSoft. 
This PR updates CourseJsonImport process to ignore missing data. The previous version of the import was raising an exception when we called slice on a missing node in the json. This version only parses if the node exists and ignores missing nodes.
There are also some updates to other parts of the system that break once this data is missing: 
1. a missing instruction mode was breaking our cache process (see issue #87) 
1. the #to_h …

Update Import to Accept Missing Resources

---

app/models/course.rb
app/models/section.rb
app/services/course_json_import.rb
db/migrate/20150612144053_move_credit_attributes_to_course.rb
db/schema.rb
doc/resources/course.yml
doc/resources/section.yml
test/fixtures/courses_example.json
test/fixtures/no_grading_basis_for_section_102.json
test/fixtures/no_instruction_mode_for_section_104.json

We originally placed these under section because we thought that the
credits might vary by section. This was incorrect. Credit Minimum and
Maximum are course-level data and should be part of the course resource.

Move Credit Minimum & Maximum to Course

---

app/models/course.rb
app/models/grading_basis.rb
app/models/section.rb
app/services/course_json_import.rb
db/migrate/20150612185245_move_grading_basis_to_course.rb
db/schema.rb
doc/resources/course.yml
doc/resources/section.yml
test/fixtures/courses_example.json
test/fixtures/no_grading_basis_for_section_102.json
test/fixtures/no_instruction_mode_for_section_104.json

It was incorrect to put Grading Basis underneath section. It is a
Course-level attribute that we exists even when the Course has no
sections. This commit moves the association to be in the correct spot.

Move Grading Basis to be a sub-resource of Course

---

app/services/course_json_import.rb

Because subject is specific to a term and campus we need to find (or create) the subject using the term_id and campus_id, otherwise it might find a subject that already exists but is for the wrong term. This results in a validation error when the course_id has already been used for that subject.
Because this requires us to use values that are not in the json, this uses find_or_create_by directly instead of going through the #parse_resource method

import Subject for the correct term

---

README.md
doc/resources/course.yml
doc/resources/courses.yml
doc/resources/day.yml
doc/resources/equivalency.yml
doc/resources/grading_basis.yml
doc/resources/instruction_mode.yml
doc/resources/instructor.yml
doc/resources/location.yml
doc/resources/meeting_pattern.yml
doc/resources/section.yml

As we moved a lot of Section resources into Course, it gave me a reason
to review the documentation and remember that it needed some work. This
commit fixes a few things.
First, I've added a courses.yml to describe the structure of the data
you get when visiting courses.json|xml.
Second, I've added some text to the Readme that points people to the
documentation.
Third, I've removed all of the incorrect descriptions that got
copy-and-pasted in to the documentation. When we can add real
descriptions, great. But until then I'd rather not have incorrect
descriptions.

Improve documentation.

---

app/services/course_json_import.rb
spec/services/course_json_import_spec.rb

Closes #111
There is a better way to do this, but it involves refactoring
course_json_import to use the Rails validations and we decided that
refactoring would happen at a later date.
For now, our fix is brute force. If the course_json is missing an
attribute that is required, we do not import that course.

Only import valid courses

---

app/models/course.rb
app/models/course_attribute.rb
app/models/grading_basis.rb
app/models/instruction_mode.rb
app/models/location.rb
app/models/section.rb
app/models/subject.rb

Fixes: https://github.com/umn-asr/courses/issues/118
It's a little awkward to have to change 7 different `to_h` methods for this one tiny tweak. I thought about doing some refactoring to make this change easier, but with the looming possibility of dumping our entire persistence layer (thanks to Chad Fennel & Solr), I decided that refactoring might be wasted effort.

Return id attributes as strings

---

config/deploy.rb

As originally documented
here: https://github.umn.edu/asrweb/queue_server/issues/118

Fix 'not a git repo' error

---

app/models/instructor.rb
app/models/section.rb
app/services/course_json_import.rb
db/migrate/20160309205534_add_print_to_instructors.rb
db/migrate/20160309205638_add_status_to_sections.rb
db/migrate/20160309205704_add_print_to_sections.rb
db/schema.rb
test/fixtures/courses_example.json
test/fixtures/no_instruction_mode_for_section_104.json

Fixes: #132, #134, #135, #136, #137, #138
The class schedule pdf generation needs these fields to properly
determine:
- which sections to print (if a section's print value is N or its status
is X, it's excluded from the PDF).
- which instructor to print for a section (if the instructor's print
is N, it is excluded from the PDF).

Import fields required by Class Schedule pdf

---

spec/lib/cache_pool_spec.rb

Fixes #126
The before block also ensures that redis-server is installed and offers
a helpful error message if not.
I'm using `spawn` because the documentation recommends it over `fork`,
since fork can be platform-specific.

Start redis for cache pool test

---

config/environments/development.rb
config/environments/production.rb
config/environments/staging.rb

We do not include the parts of rails that use these config options.
Leaving them in leads to errors when starting Rails.

Remove unused/unavailable config options

---

app/services/cache_warmer.rb
lib/tasks/json_import.rake
spec/services/cache_warmer_spec.rb

Fixes #150
Trying to make it explicit what CacheWarmer needs by passing in what it
needs.
Along with this are some test adjustments. These tests didn't fail
before because the setup implicitly returned arrays instead of the object returned
by `all`. Now the tests explicitly say "Hey, these are arrays", which
should make things clearer.
CacheWarmer still has some hidden dependencies, but they weren't
related to this issue, so I left them alone.

Pass in arrays of Terms and Campuses to CacheWarmer

---

app/services/rack_cache_manager.rb
lib/tasks/json_import.rake
spec/services/rack_cache_manager_spec.rb

Same as #150
RackCacheManager also used `product` on an ActiveRecord Relation. This
does not work in Rails 5. Fixing the same way I fixed in #151 by passing
campus/term in as params and explicitly converting them to arrays.

Fix rack cache manager's use of Product

---

config/deploy.rb

Our monit command for deploying requires sudo.

Use sudo in monit command

---

lib/cache_pool/cache_pool.gemspec

Travis-CI has had validation errors when building this gem [for awhile](https://travis-ci.org/umn-asr/courses/builds/451364046)
due to not having a proper URI in the `spec.homepage`. This fixes that
so Travis-CI will run builds now.

Fix gemspec validation error in cache_pool

---

config/schedule.rb

The Peoplesoft query completes around 1:50am so we sometimes miss the
1:30am window. This moves our import to 2am so we can catch the changes
after the query completes.

Move import cron task to 2am

---

spec/models/course_spec.rb

https://travis-ci.org/umn-asr/courses/builds/604730989?utm_source=github_status&utm_medium=notification
showed that master would fail tests when run with seed 61568
rspec bisect narrowed it down to this 'minimum' reproducible command
```
bin/rspec -f d \
'./spec/lib/cache_pool_spec.rb[1:1:1,1:1:2,1:2:1:1,1:2:1:2,1:2:1:3:1,1:2:1:4:1,1:2:2:1,1:2:2:2,1:2:2:3:1,1:2:3:1]' \
'./spec/models/course_attribute_spec.rb[1:2:2,1:2:3]' \
'./spec/models/course_spec.rb[1:1:2,1:1:6,1:1:7]' \
'./spec/models/equivalency_spec.rb[1:2:2,1:2:4]' \
'./spec/models/section_spec.rb[1:2:1,1:2:2]' \
'./spec/models/subject_spec.rb[1:2:1,1:2:2,1:2:3]' \
'./spec/services/rack_cache_manager_spec.rb[1:3:2:1]' \
--seed 61568
```
What was happening is that the random number generator would assign the
same `course_id` to 2 …

Fix flickering test due to id collision

---

Gemfile.lock

When trying to deploy to staging today, the deployment failed with some errors
for missing gems. The version of bundler on the server differed from the
version specified here. I removed these lines and deployed to staging.
That seemed to resolve the problem.

Remove BUNDLED WITH from Gemfile.lock

---

README.md

The README links and description were out of date with broken term
links.

Update README, links

---

.travis.yml

The Ruby version is already updated elsewhere (.ruby-version, etc).

Update the ruby version in .travis.yml

---

config/deploy.rb

The same as [this commit](https://github.umn.edu/sdp/uachieve_student_transfer_articulations/pull/4/commits/6ed9c6ec1dbf11242e2d3718778729df9f91632c) in
`SDP/uachieve_student_transfer_articulations`, REHL7 runs in `/etc/` so
the configuration needs to go there.

Fix monit folder

---

config/deploy/production.rb
config/deploy/staging.rb

Courses has been deployed to both of the new servers succesfully.
The DNS change hasn't happened yet, but since the Ruby version was
updated awhile ago, the repo has also not been deployable to the old
servers for awhile.
Updating the servers in the deploy config now in preparation for the DNS
change, and so that it is less to remember in every new branch.

Update deploy config for new servers

---

script/deploy

Finishes [Pivotal Tracker #183558361](https://www.pivotaltracker.com/story/show/183558361).
> https://policy.umn.edu/it/securedata-appsd
>
> Deployment Phase: Prohibit deployment when software does not pass
> security requirements in the testing phase
>
> On-going Maintenance Phase: Monitor software and dependencies for
> vulnerabilities and bugs
This will eventually be run in a container as part of our standard linting. For now, this addresses the policy linked above that came up in our Gap Analysis.
* Add bundler-audit check to deploy script

Prohibit deployment when bundle-audit fails
